FROM public.ecr.aws/lambda/python:3.12

# Instalar dependencias del sistema
RUN dnf update -y && \
    dnf install -y graphviz graphviz-devel && \
    dnf clean all


COPY requirements-lambda.txt ${LAMBDA_TASK_ROOT}
RUN pip install -r requirements-lambda.txt

# Copiar código fuentess
COPY src/ ${LAMBDA_TASK_ROOT}/src/

# Agregar directorio al PYTHONPATH
ENV PYTHONPATH="${LAMBDA_TASK_ROOT}:${PYTHONPATH}"

# Establecer el handler
CMD ["src.handler.asb_docker_handler.lambda_handler"]
